import fs from 'fs';
import path from 'path';

function walkDir(dir, callback) {
  fs.readdirSync(dir).forEach(f => {
    let dirPath = path.join(dir, f);
    let isDirectory = fs.statSync(dirPath).isDirectory();
    isDirectory ? walkDir(dirPath, callback) : callback(path.join(dir, f));
  });
}

walkDir('./src', (filePath) => {
  if (filePath.endsWith('.tsx') || filePath.endsWith('.ts')) {
    let content = fs.readFileSync(filePath, 'utf8');
    
    // Fix `}}` issues in fetch arguments generated by a previous script
    content = content.replace(/\{\s*\}\}\n*\s*\}/g, '}');
    content = content.replace(/headers:\s*\{\s*\}\}/g, 'headers: { } }');
    content = content.replace(/credentials:\s*'include',\s*headers:\s*\{\s*\}\}\s*\n*\s*\}/g, "credentials: 'include'\n        }");
    content = content.replace(/\{\s*\}\}\n\s*\}\);\s*if\s*\(res.ok\)/g, '} });\n        if (res.ok)');

    // It's safer to just do a manual replacement if we know the pattern
    content = content.replace(/\{\s*credentials:\s*'include',\s*headers:\s*\{\s*\}\}\s*\n?\s*\}/g, "{ credentials: 'include' }");
    content = content.replace(/fetch\('([^']+)',\s*\{\s*credentials:\s*'include',\s*headers:\s*\{\s*\}\}\s*\n?\s*\}/g, "fetch('$1', { credentials: 'include' }");

    fs.writeFileSync(filePath, content);
  }
});
