// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config";

const dbUrl = process.env["DATABASE_URL"];
const isValidPostgresUrl = dbUrl && (dbUrl.startsWith("postgresql://") || dbUrl.startsWith("postgres://"));

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: isValidPostgresUrl ? dbUrl : "postgresql://dummy:dummy@localhost:5432/dummy",
  },
});
